### ISSUE TITLE
Training PICARD on different dataset

### ISSUE THREAD

**Issue by majorminus66** [ElementAI/picard#12]
I'd like to train PICARD on a dataset other than Spider or CoSQL - what's the most straightforward way to do that? I'm guessing I need to make an equivalent to spider.py for my data - is there anything else that would need to be done?

**Comment by tscholak** [comment]
Hi @majorminus66!

Training a model is distinct from adapting PICARD. PICARD is just the name of our constrained decoding method, and it is fully rule-based. That means that:

1) If you already trained a model on your task, then no further training is required.
2) If you do not have a trained model already, then you want to create a file like `spider.py` for your dataset. We have based the code in the `seq2seq` folder of this repository on huggingface's translation example, https://github.com/huggingface/transformers/tree/master/examples/pytorch/translation. Therefore, proceed like you would in any other project using the huggingface stack. Perhaps your dataset is already on the huggingface hub.
3) If you have a task for which the target is a language other than SQL, then you need to write a parser for that language. PICARD's SQL parser is implemented in Haskell, see https://github.com/ElementAI/picard/blob/main/picard/src/Language/SQL/SpiderSQL/Parse.hs. If you tell me what your target language is, I can tell you how difficult it would be to write a parser for it.

Best,
Torsten

**Comment by majorminus66** [comment]
Hi Torsten, a quick question - I have the eval batch size in train.json set to 1 (as well as in eval.json), but during eval it's using batch size 2:
![image](https://user-images.githubusercontent.com/63480026/146223213-0c1a3ea6-43b2-4441-883e-1bee4afa1b08.png)

I think this might causing my training to fail due to running out of memory. I can't find where in the code it is setting the eval batch size to 2, overriding train.json.

Thanks for any help!

**Comment by tscholak** [comment]
Hi, have you set `per_device_eval_batch_size` to `1` as well?

**Comment by majorminus66** [comment]
Yep!

**Comment by tscholak** [comment]
Do you have 2 GPUs in your system?

**Comment by majorminus66** [comment]
Yes, I do!

**Comment by tscholak** [comment]
There are now plenty of datasets to train and evaluate on in the code base. By using these implementations as templates, new ones can be added easily. I'm going to close this for now. Feel free to reopen if there is a concrete issue you're running into.
