### ISSUE TITLE
Run PICARD without root privilege

### ISSUE THREAD

**Issue by zzasdf** [ElementAI/picard#19]
I have been trying to run PICARD on a machine without root privilege. Since I can't get the permission of using Docker or the apt-get from the administrator, I tried to build the environment from scratch following the Dockerfile, and I found it really difficult. Are there any other ways to run PICARD on a machine without root privilege?

**Comment by zzasdf** [comment]
Thanks. Since I don't have enough subordinate UIDs/GIDs, running the rootless docker seems to be impossible, so I haved tried the second method. But when I tried to run picard after I putted all the libraries to my directory, I met a segmentation fault. Does it mean that I have to place the libraries exactly the same place as they are in the container to let tem work properly?

**Comment by tscholak** [comment]
Hi again. No, you do t need to put everything exactly as in the image. But you do have to be complete and adjust the LD_LIBRARY_PATH env variable so that the runtime searches in the right places for the .so files. Use the ldd utility on the executables and .so files to see if that is working correctly.

**Comment by zzasdf** [comment]
It works, thanks a lot!

**Comment by tscholak** [comment]
I'm glad it worked out for you! Can I ask you to share your setup here so that others may benefit from it?

**Comment by DreamerDeo** [comment]
@zzasdf It would be very very helpful if you can share your experience about transfering the package. We are looking forward to that.

**Comment by zzasdf** [comment]
> @zzasdf It would be very very helpful if you can share your experience about setting the package.

This method relies on the Glibc version, which can't be changed without root and is very difficult to change, so it's not a perfect solution. I gave up in the end, but if your machine's ubuntu version is higher than 20.04, this method will work. You can move the lib you need from the docker to you path, and add the path to the environment variable LD_LIBRARY_PATH. In this step you may have to run the docker in an interactive way on an machine with root, and then transfer the lib file to you target machine. I can't remember which libs are necessary, but when you run picard, the error information will show which lib you lack, and then you can find them in the docker, I did it in this way.

**Comment by DreamerDeo** [comment]
@zzasdf @tscholak Thanks! It works now.
