### ISSUE TITLE
The config parameters for fine-tune T5-base without using db_content.

### ISSUE THREAD

**Issue by JiexingQi** [ElementAI/picard#21]
Hi, @tscholak ,I'm trying to reproduce your experiment for fine-tuning t5-base and get an result for 56.96 EM score and I notice that in your paper, you achieve 57.2 EM score. My config/train.json is as follows(I run it on 4 3090 GPUs and use ddp mode, it consumes about 34 hours):
```
{
    "run_name": "t5-spider",
    "model_name_or_path": "t5-base",
    "dataset": "spider",
    "source_prefix": "",
    "schema_serialization_type": "peteshaw",
    "schema_serialization_randomized": false,
    "schema_serialization_with_db_id": true,
    "schema_serialization_with_db_content": false,
    "normalize_query": true,
    "target_with_db_id": true,
    "output_dir": "./experiment/train_without_db_content",
    "cache_dir": "./transformers_cache",
    "do_train": true,
    "do_eval": true,
    "fp16": false,
    "num_train_epochs": 3072,
    "per_device_train_batch_size": 8,
    "per_device_eval_batch_size": 8,
    "gradient_accumulation_steps": 64,
    "label_smoothing_factor": 0.0,
    "learning_rate": 1e-4,
    "adafactor": true,
    "adam_eps": 1e-6,
    "lr_scheduler_type": "constant",
    "warmup_ratio": 0.0,
    "warmup_steps": 0,
    "seed": 1,
    "report_to": ["wandb"],
    "logging_strategy": "steps",
    "logging_first_step": true,
    "logging_steps": 4,
    "load_best_model_at_end": true,
    "metric_for_best_model": "exact_match",
    "greater_is_better": true,
    "save_total_limit": 128,
    "save_steps": 64,
    "evaluation_strategy": "steps",
    "eval_steps": 64,
    "predict_with_generate": true,
    "num_beams": 4,
    "num_beam_groups": 1,
    "use_picard": false
}

```
If it is convenient for you, could you please provide the parameters settings for this experiment of fine-tune t5-base that achieve 57.2 EM score. Thank you.

**Comment by tscholak** [comment]
Hi!
The configuration you posted looks good to me. Note that training runs are not fully reproducible, even for pinned random seeds. Therefore, performance will fluctuate between experiments even if the configuration stays exactly the same. It is possible that you just had bad luck and didn't reach the performance I reached in my run(s).
In any case, you are just 0.2 percentage points away from the performance I saw, which means that your model got 2 more questions out of the 1034 eval questions wrong than mine.
Best,
Torsten

**Comment by tscholak** [comment]
Would it help if I uploaded a T5-Base model?

**Comment by JiexingQi** [comment]
Thank you. @tscholak, I would appreciate if you can upload a T5-Base model. Thanks again.

**Comment by tscholak** [comment]
Hi @JiexingQi! I've added a T5-Base model, https://github.com/ElementAI/picard/commit/0426bc79856a02393261828ac9330601becf30d2

**Comment by JiexingQi** [comment]
@tscholak  Thank you!
