### ISSUE TITLE
Smaller T5 on CoSQL

### ISSUE THREAD

**Issue by DreamerDeo** [ElementAI/picard#23]
It's really an excellent work! 

And I'm wondering the results of CoSQL using T5-base/T5-Large with/without PICARD?  There only the T5-3B result has been reported in paper. Would the T5(Big model) still be competive with task-specific model if we decrease the model size?

Thanks in advance! :)

**Comment by tscholak** [comment]
Hi @DreamerDeo! I don't know, but we can find out by training and T5-Large on both Spider and CoSQL!

**Comment by DreamerDeo** [comment]
Thank for your reply! What about the result of T5-Large on CoSQL?

**Comment by tscholak** [comment]
Hey again, I haven't got those results because I haven't trained T5-Large on CoSQL yet 😉

**Comment by DreamerDeo** [comment]
Thanks!

**Comment by tscholak** [comment]
Hi @DreamerDeo,
I've added a t5.1.1.lm100k.large model for CoSQL, https://github.com/ElementAI/picard/commit/f19c49c0b232bcffe7f4fc79b3ffe0ddd382f4ef.
