### ISSUE TITLE
Add a smaller model for CoSQL

### ISSUE THREAD

**Issue by ReinierKoops** [ElementAI/picard#27]
Hi, amazing work! 

Would it be possible to add a pretrained docker model t5.1.1.lm100k.large for CoSQL?

**Comment by tscholak** [comment]
Hi @ReinierKoops!
This has been requested before, https://github.com/ElementAI/picard/issues/23 😄 
I haven't trained such a model yet. I'll look into it.

**Comment by ReinierKoops** [comment]
Thank you :)

**Comment by tscholak** [comment]
Hi @ReinierKoops,
I've added a t5.1.1.lm100k.large model for CoSQL, https://github.com/ElementAI/picard/commit/f19c49c0b232bcffe7f4fc79b3ffe0ddd382f4ef.
