### ISSUE TITLE
Why I "make eval", but it does not run on GPU?

### ISSUE THREAD

**Issue by eyuansu62** [ElementAI/picard#31]
The model just loads on CPU to eval.

**Comment by tscholak** [comment]
Hi @eyuansu62,
You need to make sure that the GPU is a supported CUDA device and is visible to PyTorch in the container. For many people, the docker command in the Makefile takes care of that, but for some it doesn't. Have a look at the following documentation, https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html.

**Comment by eyuansu62** [comment]
Thanks for your help!!!!
