### ISSUE TITLE
Error : Could not open database file in serving mode

### ISSUE THREAD

**Issue by ujjawalcse** [ElementAI/picard#43]
Hi @tscholak ,
I'm trying to run `make serve` using my own database directory.
But when i trying to get output from` fastapi` by providing db_id and question, it raises error that,
Unable to open database file
![fastapi_serving](https://user-images.githubusercontent.com/32773256/148738748-ac3e8396-eebf-4324-9642-8546b4697ac0.png)

my server terminal looks good,
![fastapi_terminal](https://user-images.githubusercontent.com/32773256/148738936-d51e9bfd-0b36-4591-a5c1-7e2d06291ae6.png)

my config/serve.json file,
```
{
    "model_path": "tscholak/cxmefzzi",
    "source_prefix": "",
    "schema_serialization_type": "peteshaw",
    "schema_serialization_randomized": false,
    "schema_serialization_with_db_id": true,
    "schema_serialization_with_db_content": true,
    "normalize_query": true,
    "target_with_db_id": true,
    "db_path": "database",
    "cache_dir": "transformers_cache",
    "num_beams": 4,
    "use_picard": true,
    "launch_picard": true,
    "picard_mode": "parse_with_guards",
    "picard_schedule": "incremental",
    "picard_max_tokens_to_check": 2,
    "device": -1
}

```
Please suggest any way how to fix this.
Thanks,

**Comment by mbuotidem** [comment]
Did you place your sqlite database named test in the database folder? Based on your screenshot, you should have it setup as : 

```
database/
  test/
    test.sqlite
```
and your sqlite database itself should be called test.

**Comment by tscholak** [comment]
Hi @ujjawalcse, @mbuotidem has the right intuition here, I would have asked the same.
Can you run
```
$ docker exec [CONTAINER ID] find /database
```
please, where `[CONTAINER ID]` is the id of the container running the serving code. This should give you
```
/database
/database/test
/database/test/test.sqlite
```
If this is the case, then please also check if the file is readable from inside the container environment.

**Comment by ujjawalcse** [comment]
Hey @tscholak @mbuotidem ,
Yaa, my folder structure is same as suggested in the repo.
Also `docker exec [CONTAINER ID] find /database` is giving the expected folder and files.
We can refer below,
![picard_issue](https://user-images.githubusercontent.com/32773256/148886694-70488395-26bd-445c-987c-a36af99a5a97.png)

**Comment by mbuotidem** [comment]
Could you try using a different database like this [one](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite)? That way, we might be able to isolate the problem. Also, what is the result of the `stat` command for your current databases? Here's mine for reference. 

![image](https://user-images.githubusercontent.com/4692052/149012130-f6965c79-5141-44bc-af21-9410fe608584.png)

**Comment by tscholak** [comment]
@mbuotidem Can you change `database` to `/database` in your configuration json file, please?

**Comment by mbuotidem** [comment]
@ujjawalcse see @tscholak's comment above. This might be the issue.

**Comment by ujjawalcse** [comment]
Thanks @tscholak @mbuotidem , Solved by changing `database` to` /database`.
Prior to that I also checked with absolute path, but it didn't work.

Thanks a lot.

**Comment by tscholak** [comment]
Glad it works, I'll close this for now. Feel free to reopen if problems reappear.
