### ISSUE TITLE
Can I just use the schema and not the entire database for serving? 

### ISSUE THREAD

**Issue by ishmeetk** [ElementAI/picard#47]
Hi. First of all great job on PICARD. I was trying to serve the model on my database schema. I am trying to understand do we need the entire database with values or can I just use the schema?  Also If I want to train or fine tune using my data, do I need the schema or the whole database with values?  Also is there an example data set I can use to first run the model without trying my data? 
Thank you in advance

**Comment by tscholak** [comment]
Hi @ishmeetk!

> can I just use the schema?

yes, that will work, too.

> If I want to train or fine tune using my data, do I need the schema or the whole database with values?

it will work either way, but you need at least the schema

> is there an example data set I can use to first run the model without trying my data?

no, not as such, though you can use the development set of the spider dataset for that purpose. you can download spider here: https://drive.google.com/uc?export=download&id=1_AckYkinAnhqmRQtGsQgUKAnTHxxX5J0

**Comment by ishmeetk** [comment]
Hi @tscholak thank you for your prompt reply. So for my_1st_database.sqlite files in the structure below:- 
```
database/
  my_1st_database/
    my_1st_database.sqlite
  my_2nd_database/
    my_2nd_database.sqlite
```
 it can just contain the column names? 
Thank you

**Comment by tscholak** [comment]
> it can just contain the column names?

yes and no. perhaps there's confusion around what these files are. they are binary files that contain sqlite databases. you create them by starting sqlite, then by creating tables and columns, and finally by inserting data. you can skip the last step :)

**Comment by ishmeetk** [comment]
@tscholak thank you for the clarification. Will do as you mentioned.
