### ISSUE TITLE
Using Picard with trained model from HuggingFace

### ISSUE THREAD

**Issue by mayankagrawal93** [ElementAI/picard#51]
Hello, Thank you for providing a great repo!
Currently I am using the pretrained model provided on Huggingface "tscholak/3vnuv1vf" for inference in following way 

```
#Text to SQL
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM,T5Tokenizer, T5ForConditionalGeneration

# tokenizer = AutoTokenizer.from_pretrained("tscholak/1wnr382e")
# tokenizer = AutoTokenizer.from_pretrained("tscholak/cxmefzzi")
tokenizer = AutoTokenizer.from_pretrained("tscholak/3vnuv1vf") 


# model = AutoModelForSeq2SeqLM.from_pretrained("tscholak/1wnr382e")
# model = AutoModelForSeq2SeqLM.from_pretrained("tscholak/cxmefzzi")
model = AutoModelForSeq2SeqLM.from_pretrained("tscholak/3vnuv1vf")

pipe = pipeline('translation_xx_to_yy', model=model, tokenizer=tokenizer)

#Inference
input_data = "how many customers bought a product with price greater than hundred and quantity greater than fight? | customer_data | customers : customer_id, name, contact, product_id, quantity | products : product_id, price"
output = pipe(input_data)[0]['translation_text']
print(output)

```

This works out fine for me. But as you have mentioned in issue #39 that when we use this model from huggingface, we are not using Picard along with it. I was thinking that is there any way I could use Picard here itself in this code above somehow by including it just before the tokenizer? 
Or do I have to completely use the docker approach you mentioned and this code cannot be used to include picard?

**Comment by tscholak** [comment]
Hi @mayankagrawal93,
There is currently no PICARD package that you could easily install and use with hf transformers. That may be possible, but is currently not planned. The answer to your question is: Please use the `eval` docker image provided here to run the code. This image ships with all dependencies necessary to run PICARD. Have a look at the implementation of the serving code, https://github.com/ElementAI/picard/blob/main/seq2seq/serve_seq2seq.py, to get an idea how PICARD is being used.

**Comment by mayankagrawal93** [comment]
Thanks for your help @tscholak ! Will use docker image then

**Comment by mayankagrawal93** [comment]
Thanks for your help @tscholak ! Will use docker image then

**Comment by mayankagrawal93** [comment]
Hi @tscholak , so I have created a docker image and everything seems to be running fine except that when I send multiple queries to docker one after another, it starts giving 

`Runtime Error : CUDA out of memory. Tried to allocate 20.0 MB (GPU 0: 14.76 GB total capacity : 13.47 GB already allocated : 5.75 MB free : 13.64 reserved in total by PyTorch)` 

I am running it on a GCP instance. My question is that if I add one more GPU of 15 GB, will the model inference work on both GPU devices together and not give OOM then? Or do I have to create another instance altogether for inference with a single GPU device of 30 GB or more? Sorry if it sounds silly

This error also occurs when I try to give more than 3 tables as sqlite files.

**Comment by tscholak** [comment]
Hi, CUDA memory consumption should not be cumulative over time. I suspect that what really is going on for you is that the longest question and schema you work with that produces the longest SQL triggers the OOM error. You can try to work with a GPU with more memory or use a smaller model. Inference on more than one GPU is currently not implemented, but can be done with model parallelism. Contributions are welcome.

**Comment by mayankagrawal93** [comment]
Alright! thanks for the clarification
