### ISSUE TITLE
What is meant by the database content in model training. 

### ISSUE THREAD

**Issue by ishmeetk** [ElementAI/picard#53]
Hi. I have a questions regarding the models trained on database content. So I am assuming it means the T5 model was trained with schema and as well as the database content. And the models which are not trained by database content and just database schema, are the other models.
 I am trying to fine-tune with my dataset and was confused on the input for training for both with database content and without. If there are are tips you could provide it will be great. Also, do you have any comments on what can change in accuracy and model output, for the models that were trained using database content vs the models trained just on database schema. Thank You

**Comment by tscholak** [comment]
Hi @ishmeetk,

Questions are always grounded in a database schema, but may additionally be grounded in related database content, e.g., entity names.

When database content is turned off, the input to the model is composed of:
* the user's natural language question,
* the database identifier, and
* a list of tables and their columns

These are arranged like this:

```
[question] | [db_id] | [table] : [column] , [column] ( ... ) , [...] | [table] : ... | ...
```

When database content is turned on, the input to the model can additionally contain content from the database. In such case, the contents of a cell that match the parts of the question are appended to the respective column identifier in the input:

```
[question] | [db_id] | [table] : [column] ( [content] , [content] ) , [column] ( ... ) , [...] | [table] : ... | ...
```

On Spider, models using database-content are typically around 1-2% better than those not using it.

**Comment by ishmeetk** [comment]
Thank you @tscholak  for your prompt reply. Your explanation is really helpful. I will keep this in mind  to fine-tune the models. Thank you once again.
