### ISSUE TITLE
compiling picard

### ISSUE THREAD

**Issue by tmgli** [ElementAI/picard#54]
Hi,

I've gone through the process of installing all picard dependencies (folly, hsthrift, etc), what I thought was required to have the environment ready to compile picard's code. However, when I reached to the point I submit the following command, I get an error (shown below). Do you know why is this error or have an intuition of how to solve it? Thanks!

`cabal install --overwrite-policy=always --install-method=copy exe:picard`

Error:
```
...
dist/build/Foreign/CPP/Dynamic.hs
Foreign/CPP/Dynamic.hsc
....
....
error: Dynamic.hsc:196:10: fatal error: cpp/cdynamic.h: No such file or directory
compilation terminated.
```

I'm using a different OS base than the one in your docker images
OS: CentOS 7

**Comment by tscholak** [comment]
Also, have you checked out all Facebook/Meta dependencies with the same commits as I have in this repository?

**Comment by tscholak** [comment]
@tmgli great, this eliminates a few causes.
It seems the issue is with some of the dependencies, most hsthrift. 
Did you run `make THRIFT_COMPILE=thrift-compiler thrift-cpp thrift-hs`?

**Comment by tmgli** [comment]
Yes, I did run all the steps before this cabal install command. I will try again the whole process to double check.

**Comment by tscholak** [comment]
I @tmgli, I'm going to close this issue due to inactivity. I hope you got it working in the end. Feel free to reopen if not.
