### ISSUE TITLE
Tips of customization needed to make it work without GPU

### ISSUE THREAD

**Issue by david-xander** [ElementAI/picard#55]
Hi,

IMHO this is one of the best models I've ever tryed. But I can only test it with huggingface's transformers. Althoug It goes pretty well, I'd like to be able to train/finetune it:

- Would it be possible that someone could point me out a few tips of what should be parametrized in the code in order to try to avoid GPU (GPU 40GB) and use it with a CPU only (i7 32GB RAM)? I've been trying to make it work following some of the tips that I've found in the previous issues. I don't mind the latency by now, just to make it work.

Thank you in advanced.

**Comment by tscholak** [comment]
Hi @david-xander!
testing is easily possible without gpu. you should be able to use https://huggingface.co/tscholak/3vnuv1vf with hf transformers on your machine. training/finetuning is a (much) different story. You will have to work with a CUDA-capable GPU. Less than 40GB of memory are fine as well, and I can help you find settings that will work for you. You may want to consider aws or gcp...

**Comment by david-xander** [comment]
Hi @tscholak Our team research team is in the process of having a multiple GPU system... Our interest is on training/finetune it. Hope to do it soon. Thank you!
