### ISSUE TITLE
error while building dev-image: ssh connection to github.com timed out.

### ISSUE THREAD

**Issue by kotalaraghava** [ElementAI/picard#63]
Hey @tscholak,

I have been trying to build a new image to do the deployment in sagemaker. 

![text-sql-error](https://user-images.githubusercontent.com/72073231/155108139-65517838-3307-4069-a635-751f21adb057.PNG)

in the above command I removed ` --builder buildx-local ` argument as it was giving other `open /home/ubuntu/.docker/buildx/instances/buildx-local: no such file or directory
`

I tried debugging ssh timed out error by adding ssh key of my server to GitHub and when I ` ssh -T git@github.com
`it's able to connect to Github successfully. 

But when I run through the build image command, the connection is getting timed out. I know it's not pertaining to Picard, but I have been trying to solve this for quite some time :).

Any help or suggestions are appreciated.

**Comment by tscholak** [comment]
Hi,

Why does deploying on sage master require building a new image?

**Comment by kotalaraghava** [comment]
Hey,

We need to set WORKDIR to `/opt/program/`, to make sagemaker load the API automatically.

I am following this [referece ](https://towardsdatascience.com/bring-your-own-container-with-amazon-sagemaker-37211d8412f4)

So I need to build the image with the above change to make it work with sagemaker.

kindly provide suggestions, if its not the proper way of deploying in sagemaker 😃

**Comment by tscholak** [comment]
There's a paywall and I can't read the article. Instead of rebuilding the whole image, perhaps you can make a Dockerfile that imports the PICARD's eval image in `FROM` and then adds a link from `/app` to `/opt/program`.

**Comment by tscholak** [comment]
@kotalaraghava Has this been addressed? The buildx builder is sometimes tricky to get working. Feel free to reopen.
