### ISSUE TITLE
Do inference use database content in the result

### ISSUE THREAD

**Issue by ishmeetk** [ElementAI/picard#64]
I was trying to analyze few of the results and had a question in the content of database is used to make the inference? I saw that during training there arr two ways, with or without database content. So the parameters are trained accordingly. But is it used in inference or database content in inference is just to query and not to actually generate the sql query. 
Thank You in advance.

**Comment by tscholak** [comment]
Hi @ishmeetk,
The option is also available during inference. If active, database lookups are performed to enrich the model's input. So, yes, database content is used to generate the SQL query.

**Comment by ishmeetk** [comment]
Thank you @tscholak for your prompt reply. It clarifies my question. 
Also, when we try to train T5 model with our own database, the input looks like below :-
[question] | [db_id] | [table] : [column] ( [content] , [content] ) , [column] ( ... ) , [...] | [table] : ... | ...
Here, for each input, the content will be for the corresponding  question, or for every input, we input the entire column, content? 
And if I am using my own dataset, what is the best script to follow so that it is compatible to use Picard after training. 
Thank You once again !

**Comment by tscholak** [comment]
Hi @ishmeetk,
It appears to me you are trying to (re-)implement your own training loop and data pre- and post-processor for text-to-sql translation with T5. Perhaps you need to use tensorflow at Apple? Whatever the reason, I think the best way to help you is to tell you where in this repo you can find relevant code snippets that will make that task easier for you.
The input to the model is assembled here: https://github.com/ElementAI/picard/blob/main/seq2seq/utils/spider.py#L10-L15.
And the schema serialization code is here: https://github.com/ElementAI/picard/blob/main/seq2seq/utils/dataset.py#L331-L403.
The latter calls `get_database_matches` from https://github.com/ElementAI/picard/blob/main/seq2seq/utils/bridge_content_encoder.py#L224. This code is originally from Salesforce's BRIDGE model, and it tries to find matches between column values and parts of speech in the question. Only matching cell values are used, and by default at most 2 at a time.

After you have trained your own T5 text-to-SQL model, it is best to use the eval docker image provided here to evaluate it with the PICARD constrained beam search algorithm. If your T5 model checkpoint is created using tensor flow, then you first have to convert it to PyTorch. Huggingface has a script for that.

**Comment by ishmeetk** [comment]
Thank you soo much @tscholak. I will refer the above code. So the PICARD layer comes into play only at Eval level? How can I use model trained by me with Picard in the serve mode? Like how do I "attach" the PICARD layer? 
Thank you once again for your help!

**Comment by tscholak** [comment]
Hi @ishmeetk,
The PICARD "layer" is implemented as a wrapper class around the the AutoModel class in huggingface, see here: https://github.com/ElementAI/picard/blob/5ff827fa65c719ff975a37bd1d6940214731f3f5/seq2seq/utils/picard_model_wrapper.py#L106. PICARD has no trainable components. The `PicardLogitsProcessor` is a plugin to the `generate` function that is used by huggingface sequence models to infer the target. Tokens are send to an external process that decides whether or not the token is admissible. That external process is where the parsing happens. The communication between the python process and the external parser is handled by Thrift.

**Comment by tscholak** [comment]
I @ishmeetk, I'm going to close this issue. Feel free to reopen if my answer wasn't satisfying.

**Comment by ishmeetk** [comment]
@tscholak thank u soo much for your explanation. Much appreciated.
