### ISSUE TITLE
Baseline or starting point of PICARD

### ISSUE THREAD

**Issue by david-xander** [ElementAI/picard#65]
Hello @tscholak,

You mentioned a baseline model that I can't find defined in the paper or in the GitHub readme, Youtube video... Would it be possible to know the baseline that this model improved?

Thank you very much in advanced.

**Comment by tscholak** [comment]
Hi @david-xander,
The baseline is always a model without constrained inference. If you scroll down to the table in the readme, rows come always in pairs: same model, but once with and once without PICARD constrained inference.
People tend to think PICARD is the name of a model. It's not. It's the name of the method we propose for constraining the beam search to valid code.

**Comment by david-xander** [comment]
Very clarifying! Thank you!
