### ISSUE TITLE
Inquire about Training Time

### ISSUE THREAD

**Issue by JL5173** [ElementAI/picard#77]
Dear author,

Thanks for your open-source coding. It's very clean and inspiring. According to your paper, you reported the training times and epochs, but I didn't see how many A100s that you achieve this training and inference speed. May I ask whether you train spider in a single A100 for the numbers you reported in your paper or several A100s parallel for more than 3000 epochs? Thanks.

**Comment by tscholak** [comment]
Hi, I used just one for this work.

**Comment by JL5173** [comment]
Thanks for your response, may I ask how much total time (approximately) did you train for 3000 epochs with t5-3b for spider? Thanks

**Comment by tscholak** [comment]
You should have expect the model to achieve peak performance on the dev set after 2-3 days of training on one A100. Training for the full number of steps (3000) at batch size 2048 is not necessary to achieve the best performance.

**Comment by JL5173** [comment]
Ok, got it, understand! Yes I also think 3000 is too long. But I like your professional coding styles. Learn a lot from your codings. Thanks

**Comment by tscholak** [comment]
Thanks 😊 
Closing this issue since your question was answered.
