### ISSUE TITLE
About evaluation.

### ISSUE THREAD

**Issue by huybery** [ElementAI/picard#79]
Hi, thanks for your nice work!
Are Picard's exact-set-match and test-suite-execution accuracy exactly the same (71.9%)?

**Comment by tscholak** [comment]
Yes and no. The exact-set-match accuracy on **test** is 71.9%, and the test-suite accuracy on **dev** is also 71.9%, coincidentally.

**Comment by huybery** [comment]
Thanks for your reply, I was stupid :)
