### ISSUE TITLE
Hugging Face model

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [ElementAI/picard#81]
Hello, 

First, thank you for this amazing work. 

I use the model  ` tscholak/1zha5ono`  from hugging Face. According to the table in your github, the exact match should be  59.4 %. However, I got 37.8%. 

I executed the evaluation as it follows:

`
python3 evaluation.py --gold evaluation_examples/gold_example.txt --pred results/hugging_face/T5_base_1zha5ono/1zha5ono.txt --etype "all" --db database/ --table evaluation_examples/examples/tables.json
`

Thank you so much in advance.

**Comment by tscholak** [comment]
Hi, This is surprising. How were these predictions obtained?

**Comment by tscholak** [comment]
Hi, Am I correct in assuming that you have hardcoded the inputs using the picard codebase ahead of time?
> list_query = get_info_query(path_dir, file_name)
Can you please send me all input-output pairs via email? You can use first name dot last name at gmail. Then I can compare with what I've got. Thanks!

**Comment by JessicaLopezEspejel** [comment]
Hello, 

I sent you the files. 

Thank you very much.

**Comment by JessicaLopezEspejel** [comment]
Hello, 

Excuse me, did you receive the files? I am afraid I had a mistake in the email.

Thank you.

**Comment by JessicaLopezEspejel** [comment]
Hello, 

The problem was in my inputs, I mean, in the preprocessing. 

Thank you so much.

**Comment by tscholak** [comment]
Glad you could figure it out. Unfortunately, I could not afford the time looking at your files.
