### ISSUE TITLE
Test performances for t5.1.1.lm100k.large and probably t5.1.1.lm100k.base

### ISSUE THREAD

**Issue by freesunshine0316** [ElementAI/picard#84]
Hi, 

Is it possible to get the Test-set scores of Spider for t5.1.1.lm100k.large and possibly t5.1.1.lm100k.base? 
I guess lots of people are working on these checkpoints, as they are more computationally affordable.
Thanks.

**Comment by tscholak** [comment]
Hi, I think you can get an idea from the dev scores already. The architecture and approach is the same, performance on the test set is easy to estimate. I don't want to ask the maintainers of the leaderboard to run prediction on the test set for such a minor contribution.
