### ISSUE TITLE
GPU not use

### ISSUE THREAD

**Issue by Gyyz** [ElementAI/picard#95]
Anyone have any idea? I set up the experiments by the instruction, and everything looks fine, but when I run 'make train', the experiments stuck and never start to train, and my A100 is not used. Thanks. My CUDA Version: 11.5. 

![Screenshot from 2022-05-30 16-41-02](https://user-images.githubusercontent.com/22828349/170954020-3eb0d093-06b9-4a8b-a607-0b90868fa4c0.png)

**Comment by valadhi** [comment]
Adding the "--gpus=all" flag in the Makefile to the docker run instruction worked for me

**Comment by Gyyz** [comment]
> Adding the "--gpus=all" flag in the Makefile to the docker run instruction worked for me

@valadhi Thanks, seems also works for me.
